# Generated by Django 6.0.2 on 2026-06-09 17:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_turno_ventaturno'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventaturno',
            name='devuelto',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ventaturno',
            name='fecha_venta',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
